- name: Install requider packages
  become: true
  apt:
    name: [ "gnome-terminal", "ca-certificates", "curl", "gnupg", "lsb-release" ]
  tags:
    - docker
- name: Add Docker official GPG key download
  become: true
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  tags:
    - docker
- name: Docker PPA setting
  become: true
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  tags:
    - docker
- name: Apt update
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  tags:
    - docker