- name: Install Volta
  shell: curl -L https://get.volta.sh > ~/.volta-installer && chmod +x ~/.volta-installer && ~/.volta-installer
  become: true
  become_method: su
  become_user: "{{ user_name }}"
  tags: 
    - install
    - node
- name: Install node
  shell: ~/.volta/bin/volta install node@lts
  become: true
  become_method: su
  become_user: "{{ user_name }}"
  tags:
    - install
    - node