- name: Remove neovim
  become: true
  become_method: su
  become_user: "{{ user_name }}"
  shell: rm -rf ~/neovim
  tags:
    - neovim
- name: Get Packer
  become: true
  become_method: su
  become_user: "{{ user_name }}"
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - neovim
- name: Clone Neovim
  become: true
  become_method: su
  become_user: "{{ user_name }}"
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - neovim
- name: Build neovim
  become: true
  become_method: su
  become_user: "{{ user_name }}"
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
  tags:
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - neovim